In [1]:
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import preprocess_input
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score



In [2]:

TEST_DIR = r"C:\Users\KristianHaltenJensen\Noroff\Bachelor\LWDCD final test"
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
MODEL_PATH = "VGG16_finetuned_LWDCD.keras"   # change if needed


In [3]:

test_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)

print("\nTest class indices:")
print(test_generator.class_indices)



Found 45 images belonging to 3 classes.

Test class indices:
{'Healthy Wheat': 0, 'Leaf Rust': 1, 'Wheat Loose Smut': 2}


In [4]:
model = load_model(MODEL_PATH)



In [5]:
test_loss, test_acc = model.evaluate(test_generator, verbose=1)
print(f"\nTest Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_acc:.4f}")

pred_probs = model.predict(test_generator, verbose=1)
y_pred = np.argmax(pred_probs, axis=1)
y_true = test_generator.classes
class_names = list(test_generator.class_indices.keys())

print("\nAccuracy Score:")
print(f"{accuracy_score(y_true, y_pred):.4f}")

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))

print("\nConfusion Matrix:")
print(confusion_matrix(y_true, y_pred))



C:\Users\KristianHaltenJensen\anaconda4\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


2/2 ━━━━━━━━━━━━━━━━━━━━ 4s 699ms/step - accuracy: 0.7729 - loss: 1.0240

Test Loss: 0.9021
Test Accuracy: 0.8000
2/2 ━━━━━━━━━━━━━━━━━━━━ 3s 864ms/step

Accuracy Score:
0.8000

Classification Report:
                  precision    recall  f1-score   support

   Healthy Wheat       1.00      0.40      0.57        15
       Leaf Rust       0.62      1.00      0.77        15
Wheat Loose Smut       1.00      1.00      1.00        15

        accuracy                           0.80        45
       macro avg       0.88      0.80      0.78        45
    weighted avg       0.88      0.80      0.78        45


Confusion Matrix:
[[ 6  9  0]
 [ 0 15  0]
 [ 0  0 15]]
